### PR TITLE
Make fs-extra a dependency

### LINKED ISSUE #204: cannot find module 'fs-extra'
Since updating to 1.4.0 I am getting the following error when running grunt cacheBust:

```
Loading "cachebust.js" tasks...ERROR
>> Error: Cannot find module 'fs-extra'
```

Downgrading to 1.3.0 fixes the issue for me.

### PR DESCRIPTION
**Pull request by charwking**
Fixes #204 by moving `fs-extra` to the dependencies section in the `package.json` file.

### CODE REVIEW

**Comment by hollandben** [comment]
Thanks @charwking
