### ISSUE TITLE
cannot find module 'fs-extra'

### ISSUE THREAD

**Issue by davemac** [hollandben/grunt-cache-bust#204]
Since updating to 1.4.0 I am getting the following error when running grunt cacheBust:

```
Loading "cachebust.js" tasks...ERROR
>> Error: Cannot find module 'fs-extra'
```

Downgrading to 1.3.0 fixes the issue for me.

**Comment by Hlsgs** [comment]
+1

**Comment by charwking** [comment]
v1.4.0 started using [`fs-extra` in the cachebust.js file](https://github.com/hollandben/grunt-cache-bust/blob/master/tasks/cachebust.js#L3), but it was [added to `package.json` as a devDependency](https://github.com/hollandben/grunt-cache-bust/blob/master/package.json#L23). This means the `fs-extra` module isn't installed when `grunt-cache-bust` is installed, and thus the "cannot find module" error. `package.json` should be updated to list `fs-extra` as a peerDependency or a dependency.

To temporarily work-around this, you can "manually" install `fs-extra` in your repository:

```shell
npm install -D grunt-cache-bust
npm install -D fs-extra
```

**Comment by kanthi7** [comment]
I tried this, when using npm install fs-extra, it added to dev-dependencies. So I even tried by moving it to dependencies, still when deploying in Jenkins, ending up in same error. Can somebody help, please?
